apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: posts-api-monitor
  namespace: monitoring
  labels:
    release: kube-monitor
spec:
  selector:
    matchLabels:
      app: posts-api
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
  namespaceSelector:
    matchNames:
      - default
