apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
spec:
  template:
    spec:
      containers:
        - name: prisma
          image: posts-api:local
          command: ['npx', 'prisma', 'db', 'push']
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: posts-backend-secrets
                  key: database-url
      restartPolicy: Never
  backoffLimit: 1
