name: CI

on:
  push:
    branches:
      - main

jobs:
  build-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run format

      - name: Run Lint
        run: npm run lint

      - name: Type Check
        run: npm run typecheck

      - name: Run Tests
        run: npm test

      - name: Validate Prisma schema
        run: npm run prisma:validate
